### ISSUE TITLE
关于“finishpage.dgstu.tk”接口，能否加上评分的五角星？

### ISSUE THREAD

**Issue by NianBroken** [huoyiming/youthstudy-tool#2]
在最新的青年大学习官方完成页中存在评分的五角星，但“finishpage.dgstu.tk”接口没有。

**Comment by NianBroken** [comment]
@huoyiming

**Comment by huoyiming** [comment]
see: https://github.com/Chenghow/youthstudy-tool/issues/27
这是自用仓库，请不要在这提issue
